import { ComplexityLevel } from '@/types';

export interface StaticSubTopic {
  slug: string;
  name: string;
  description: string;
}

export interface StaticTopic {
  slug: string;
  name: string;
  description: string;
  icon_name: string;
  color_primary: string;
  color_secondary: string;
  sort_order: number;
  sub_topics: StaticSubTopic[];
  complexity_labels: Record<ComplexityLevel, string>;
}

export const TOPICS: StaticTopic[] = [
  {
    slug: 'culinary-arts',
    name: 'Culinary Arts',
    description: 'Discover the science and art behind great food',
    icon_name: 'restaurant',
    color_primary: '#F97316',
    color_secondary: '#FED7AA',
    sort_order: 0,
    sub_topics: [
      { slug: 'flavor-science',     name: 'Flavor Science & Pairing',  description: 'Why certain flavors work together' },
      { slug: 'cooking-techniques', name: 'Cooking Techniques',         description: 'Master the core methods of cooking' },
      { slug: 'world-cuisines',     name: 'World Cuisines',             description: 'A tour of global food cultures' },
      { slug: 'baking-pastry',      name: 'Baking & Pastry',            description: 'The precise science behind baking' },
    ],
    complexity_labels: { beginner: 'Kitchen Curious', intermediate: 'Home Chef', advanced: 'Culinary Scientist' },
  },
  {
    slug: 'automotive',
    name: 'Cars & Automotive',
    description: 'From engines to EVs — how cars work and why it matters',
    icon_name: 'car-sport',
    color_primary: '#6366F1',
    color_secondary: '#C7D2FE',
    sort_order: 1,
    sub_topics: [
      { slug: 'how-engines-work',   name: 'How Engines Work',         description: 'Internal combustion and beyond' },
      { slug: 'ev-future-tech',     name: 'EV & Future Tech',         description: 'Electric vehicles and what is coming next' },
      { slug: 'racing-performance', name: 'Racing & Performance',     description: 'Speed, aerodynamics, and motorsport' },
      { slug: 'car-history',        name: 'Car History & Culture',    description: 'The machines and moments that defined driving' },
    ],
    complexity_labels: { beginner: 'Weekend Driver', intermediate: 'Gearhead', advanced: 'Automotive Engineer' },
  },
  {
    slug: 'space-astronomy',
    name: 'Space & Astronomy',
    description: 'Explore the cosmos, from our solar system to black holes',
    icon_name: 'planet',
    color_primary: '#8B5CF6',
    color_secondary: '#DDD6FE',
    sort_order: 2,
    sub_topics: [
      { slug: 'solar-system',      name: 'Solar System',              description: 'Our cosmic neighborhood' },
      { slug: 'stars-galaxies',    name: 'Stars & Galaxies',          description: 'Life cycles of stars and galaxy structure' },
      { slug: 'black-holes',       name: 'Black Holes & Cosmology',   description: 'Extreme objects and the origin of the universe' },
      { slug: 'space-exploration', name: 'Space Exploration',         description: 'Missions, rockets, and humanity in space' },
    ],
    complexity_labels: { beginner: 'Stargazer', intermediate: 'Amateur Astronomer', advanced: 'Astrophysicist' },
  },
  {
    slug: 'physics',
    name: 'Physics',
    description: 'The fundamental laws that govern everything around us',
    icon_name: 'flash',
    color_primary: '#3B82F6',
    color_secondary: '#BFDBFE',
    sort_order: 3,
    sub_topics: [
      { slug: 'mechanics-motion',  name: 'Mechanics & Motion',        description: 'Forces, energy, and how things move' },
      { slug: 'thermodynamics',    name: 'Thermodynamics',            description: 'Heat, entropy, and the laws of energy' },
      { slug: 'quantum-mechanics', name: 'Quantum Mechanics',         description: 'The weird world at the smallest scales' },
      { slug: 'electromagnetism',  name: 'Electromagnetism',          description: 'Fields, waves, and the nature of light' },
    ],
    complexity_labels: { beginner: 'Curious Observer', intermediate: 'Problem Solver', advanced: 'Theoretical Physicist' },
  },
  {
    slug: 'chemistry',
    name: 'Chemistry',
    description: 'Atoms, reactions, and the building blocks of matter',
    icon_name: 'flask',
    color_primary: '#10B981',
    color_secondary: '#A7F3D0',
    sort_order: 4,
    sub_topics: [
      { slug: 'elements-periodic', name: 'Elements & Periodic Table', description: 'Atoms, elements, and the table that organizes them' },
      { slug: 'chemical-reactions',name: 'Chemical Reactions',        description: 'How substances transform and combine' },
      { slug: 'organic-chemistry', name: 'Organic Chemistry',         description: 'Carbon compounds and the chemistry of life' },
      { slug: 'materials-science', name: 'Materials Science',         description: 'Metals, polymers, and engineered materials' },
    ],
    complexity_labels: { beginner: 'Lab Newcomer', intermediate: 'Lab Technician', advanced: 'Research Chemist' },
  },
  {
    slug: 'biology',
    name: 'Biology',
    description: 'Life itself — from cells to ecosystems',
    icon_name: 'leaf',
    color_primary: '#22C55E',
    color_secondary: '#BBF7D0',
    sort_order: 5,
    sub_topics: [
      { slug: 'cell-biology', name: 'Cell Biology',        description: 'The fundamental unit of life' },
      { slug: 'genetics-dna', name: 'Genetics & DNA',      description: 'Heredity, genes, and the code of life' },
      { slug: 'evolution',    name: 'Evolution',           description: 'How life changes over time' },
      { slug: 'ecology',      name: 'Ecology & Ecosystems',description: 'How living things interact with their world' },
    ],
    complexity_labels: { beginner: 'Nature Lover', intermediate: 'Biologist', advanced: 'Research Scientist' },
  },
  {
    slug: 'psychology-social',
    name: 'Psychology & Social Skills',
    description: 'Understand yourself and connect better with others',
    icon_name: 'people',
    color_primary: '#EC4899',
    color_secondary: '#FBCFE8',
    sort_order: 6,
    sub_topics: [
      { slug: 'cognitive-biases',      name: 'Cognitive Biases',          description: 'The mental shortcuts that fool us' },
      { slug: 'emotional-intelligence',name: 'Emotional Intelligence',     description: 'Understanding and managing emotions' },
      { slug: 'social-dynamics',       name: 'Social Dynamics',            description: 'How groups and relationships work' },
      { slug: 'mental-health',         name: 'Mental Health Basics',       description: 'Foundations of psychological well-being' },
    ],
    complexity_labels: { beginner: 'Self-Aware', intermediate: 'Empathic Thinker', advanced: 'Applied Psychologist' },
  },
  {
    slug: 'history',
    name: 'History',
    description: 'The events and people that shaped our world',
    icon_name: 'time',
    color_primary: '#B45309',
    color_secondary: '#FDE68A',
    sort_order: 7,
    sub_topics: [
      { slug: 'ancient-civilizations', name: 'Ancient Civilizations',  description: 'Egypt, Rome, Greece, and the ancient world' },
      { slug: 'medieval-renaissance',  name: 'Medieval & Renaissance', description: 'The Middle Ages through the Renaissance' },
      { slug: 'modern-history',        name: 'Modern History',         description: 'From the Industrial Revolution to WWII' },
      { slug: 'contemporary-world',    name: 'Contemporary World',     description: 'The world from 1945 to today' },
    ],
    complexity_labels: { beginner: 'History Fan', intermediate: 'Historian', advanced: 'Historical Analyst' },
  },
  {
    slug: 'engineering',
    name: 'Engineering',
    description: 'From structures to machines — the principles of applied science',
    icon_name: 'cog',
    color_primary: '#6B7280',
    color_secondary: '#D1D5DB',
    sort_order: 8,
    sub_topics: [
      { slug: 'civil-infrastructure',name: 'Civil & Infrastructure',   description: 'Roads, bridges, buildings, and urban systems' },
      { slug: 'mechanical-engineering',name: 'Mechanical Engineering',  description: 'Machines, engines, and mechanical systems' },
      { slug: 'electrical-engineering',name: 'Electrical Engineering', description: 'Power, circuits, and electromagnetic systems' },
      { slug: 'materials-engineering',name: 'Materials Engineering',    description: 'How materials are engineered and optimized' },
    ],
    complexity_labels: { beginner: 'Tech Explorer', intermediate: 'Engineer', advanced: 'Senior Engineer' },
  },
  {
    slug: 'software',
    name: 'Software',
    description: 'How software systems, AI, and the internet work',
    icon_name: 'at-outline',
    color_primary: '#06B6D4',
    color_secondary: '#A5F3FC',
    sort_order: 9,
    sub_topics: [
      { slug: 'how-internet-works',  name: 'How the Internet Works',  description: 'Networks, protocols, and the web' },
      { slug: 'ai-machine-learning', name: 'AI & Machine Learning',   description: 'How machines learn and what it means' },
      { slug: 'cybersecurity',       name: 'Cybersecurity',           description: 'Protecting systems and understanding threats' },
      { slug: 'software-architecture',name: 'Software Architecture',   description: 'Systems design and scalable applications' },
    ],
    complexity_labels: { beginner: 'Digital Curious', intermediate: 'Developer', advanced: 'Systems Architect' },
  },
  {
    slug: 'coding',
    name: 'Coding',
    description: 'Programming languages and the art of writing code',
    icon_name: 'code',
    color_primary: '#0891B2',
    color_secondary: '#A5F3FC',
    sort_order: 10,
    sub_topics: [
      { slug: 'programming-concepts',name: 'Programming Concepts',    description: 'Variables, functions, and programming logic' },
      { slug: 'data-structures',     name: 'Data Structures',         description: 'Arrays, trees, graphs, and algorithms' },
      { slug: 'web-development',     name: 'Web Development',         description: 'HTML, CSS, JavaScript, and web frameworks' },
      { slug: 'mobile-gamedev',      name: 'Mobile & Game Dev',       description: 'Building apps and games for mobile platforms' },
    ],
    complexity_labels: { beginner: 'Code Curious', intermediate: 'Developer', advanced: 'Software Engineer' },
  },
  {
    slug: 'art-design',
    name: 'Art & Design',
    description: 'Color, form, and creativity — the principles of visual art',
    icon_name: 'color-palette',
    color_primary: '#F43F5E',
    color_secondary: '#FECDD3',
    sort_order: 11,
    sub_topics: [
      { slug: 'color-theory',      name: 'Color Theory',             description: 'How color works and why it matters' },
      { slug: 'art-history',       name: 'Art History Movements',    description: 'From Renaissance to contemporary art' },
      { slug: 'design-principles', name: 'Design Principles',        description: 'Layout, hierarchy, and visual communication' },
      { slug: 'digital-art',       name: 'Digital Art & Media',      description: 'Creating and understanding digital visuals' },
    ],
    complexity_labels: { beginner: 'Creative Explorer', intermediate: 'Visual Artist', advanced: 'Design Theorist' },
  },
  {
    slug: 'music',
    name: 'Music',
    description: 'Theory, history, and the science of sound',
    icon_name: 'musical-notes',
    color_primary: '#A855F7',
    color_secondary: '#E9D5FF',
    sort_order: 12,
    sub_topics: [
      { slug: 'music-theory',     name: 'Music Theory',              description: 'Notes, scales, chords, and rhythm' },
      { slug: 'instruments',      name: 'Instruments & Orchestration',description: 'The sounds of each instrument family' },
      { slug: 'music-history',    name: 'Music History & Genres',    description: 'From classical to hip-hop and everything between' },
      { slug: 'music-production', name: 'Production & Recording',    description: 'How music is made in the studio' },
    ],
    complexity_labels: { beginner: 'Music Lover', intermediate: 'Musician', advanced: 'Composer & Producer' },
  },
  {
    slug: 'sports-fitness',
    name: 'Sports & Fitness',
    description: 'The science of movement, training, and peak performance',
    icon_name: 'fitness',
    color_primary: '#EF4444',
    color_secondary: '#FECACA',
    sort_order: 13,
    sub_topics: [
      { slug: 'sports-science',    name: 'Sports Science & Biomechanics',description: 'How the body moves and performs' },
      { slug: 'training-nutrition',name: 'Training & Nutrition',         description: 'Building fitness and fueling performance' },
      { slug: 'sports-history',    name: 'Sports History & Culture',     description: 'The moments and athletes that defined sports' },
      { slug: 'mind-performance',  name: 'Mind & Performance',           description: 'Psychology, focus, and mental toughness' },
    ],
    complexity_labels: { beginner: 'Active Beginner', intermediate: 'Athlete', advanced: 'Performance Coach' },
  },
  {
    slug: 'nature-environment',
    name: 'Nature & Environment',
    description: 'Biodiversity, climate, and the living planet',
    icon_name: 'earth',
    color_primary: '#16A34A',
    color_secondary: '#BBF7D0',
    sort_order: 14,
    sub_topics: [
      { slug: 'climate-weather',      name: 'Climate & Weather',         description: 'Atmosphere, weather systems, and climate change' },
      { slug: 'biodiversity',         name: 'Biodiversity',              description: 'The variety of life on Earth and why it matters' },
      { slug: 'ocean-marine',         name: 'Ocean & Marine Life',       description: 'The deep sea and the creatures within it' },
      { slug: 'environmental-science',name: 'Environmental Science',     description: 'Human impact and paths to sustainability' },
    ],
    complexity_labels: { beginner: 'Nature Fan', intermediate: 'Environmentalist', advanced: 'Ecologist' },
  },
  {
    slug: 'finance-economics',
    name: 'Finance & Economics',
    description: 'Money, markets, and how economies actually function',
    icon_name: 'trending-up',
    color_primary: '#EAB308',
    color_secondary: '#FEF08A',
    sort_order: 15,
    sub_topics: [
      { slug: 'personal-finance',  name: 'Personal Finance',          description: 'Budgeting, saving, and building wealth' },
      { slug: 'markets-investing', name: 'Markets & Investing',       description: 'Stocks, bonds, and how markets work' },
      { slug: 'economic-theory',   name: 'Economic Theory',           description: 'Supply, demand, and macroeconomic models' },
      { slug: 'global-economics',  name: 'Global Economics',          description: 'Trade, currencies, and the world economy' },
    ],
    complexity_labels: { beginner: 'Money Conscious', intermediate: 'Investor', advanced: 'Economist' },
  },
  {
    slug: 'philosophy',
    name: 'Philosophy',
    description: 'Big questions, logical thinking, and the examined life',
    icon_name: 'book',
    color_primary: '#64748B',
    color_secondary: '#CBD5E1',
    sort_order: 16,
    sub_topics: [
      { slug: 'ancient-philosophy', name: 'Ancient Philosophy',        description: 'Socrates, Plato, Aristotle, and the Stoics' },
      { slug: 'ethics-morality',    name: 'Ethics & Morality',         description: 'How to think about right and wrong' },
      { slug: 'logic-thinking',     name: 'Logic & Critical Thinking', description: 'Arguments, fallacies, and clear reasoning' },
      { slug: 'philosophy-of-mind', name: 'Philosophy of Mind',        description: 'Consciousness, identity, and what it means to think' },
    ],
    complexity_labels: { beginner: 'Deep Thinker', intermediate: 'Philosopher', advanced: 'Logician' },
  },
  {
    slug: 'languages-linguistics',
    name: 'Languages & Linguistics',
    description: 'How language works, where words come from, why it matters',
    icon_name: 'chatbubbles',
    color_primary: '#0EA5E9',
    color_secondary: '#BAE6FD',
    sort_order: 17,
    sub_topics: [
      { slug: 'how-language-works',   name: 'How Language Works',         description: 'Phonology, syntax, and structure of language' },
      { slug: 'world-languages',      name: 'World Languages Overview',   description: 'The diversity of human languages' },
      { slug: 'etymology',            name: 'Etymology & Word Origins',   description: 'Where words come from and how they change' },
      { slug: 'communication-science',name: 'Communication Science',      description: 'How we understand and misunderstand each other' },
    ],
    complexity_labels: { beginner: 'Word Curious', intermediate: 'Linguist', advanced: 'Language Researcher' },
  },
  {
    slug: 'health-wellness',
    name: 'Health & Wellness',
    description: 'Human anatomy, nutrition, sleep, and mental well-being',
    icon_name: 'heart',
    color_primary: '#F87171',
    color_secondary: '#FECACA',
    sort_order: 18,
    sub_topics: [
      { slug: 'human-anatomy',    name: 'Human Anatomy',    description: 'How the body is structured and functions' },
      { slug: 'nutrition-science',name: 'Nutrition Science',description: 'Food, metabolism, and what your body needs' },
      { slug: 'sleep-recovery',   name: 'Sleep & Recovery', description: 'Why rest is as important as training' },
      { slug: 'mental-wellness',  name: 'Mental Wellness',  description: 'Stress, resilience, and emotional health' },
    ],
    complexity_labels: { beginner: 'Health Aware', intermediate: 'Wellness Practitioner', advanced: 'Health Scientist' },
  },
  {
    slug: 'geography-travel',
    name: 'Geography & Travel',
    description: 'Cultures, landscapes, and the geopolitics of our world',
    icon_name: 'map',
    color_primary: '#FB923C',
    color_secondary: '#FED7AA',
    sort_order: 19,
    sub_topics: [
      { slug: 'physical-geography', name: 'Physical Geography',      description: 'Landforms, oceans, and natural features' },
      { slug: 'world-cultures',     name: 'World Cultures',          description: 'Traditions, languages, and ways of life' },
      { slug: 'geopolitics',        name: 'Geopolitics',             description: 'Power, borders, and international relations' },
      { slug: 'natural-wonders',    name: 'Natural Wonders',         description: 'The most spectacular places on Earth' },
    ],
    complexity_labels: { beginner: 'Globe Trotter', intermediate: 'World Explorer', advanced: 'Geopolitical Analyst' },
  },
];

export function getTopicBySlug(slug: string): StaticTopic | undefined {
  return TOPICS.find(t => t.slug === slug);
}
